version: "3.8"

services:
  db-mysql:
    container_name: naem_database
    image: mysql
    platform: linux/amd64
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    networks:
      - springboot-mysql-net

  redis-docker:
    image: redis:alpine
    command: redis-server --port ${REDIS_LOCAL_PORT}
    container_name: "docker-redis"
    volumes:
      - ./docker-data/redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}

  application:
    container_name: naem_application
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://localhost:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC&characterEncoding=UTF-8",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create"
        }'
    depends_on:
      - db-mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge