package naem.server.domain;

public enum TagType {

    MENTAL, INTELLECTUAL, RETARDED,
    VISUAL, DEAFNESS, AUTISTIC,
    SPEECH, BRAIN_LESION, KIDNEY,
    RESPIRATORY, FACIAL, URETHRAL,
    HEART, RIVER, EPILEPSY, ETC
}
